In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import f1_score, roc_curve, auc, roc_auc_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

In [2]:
# Load the dataset as df
train_data_path = 'D:/University documents/Year 4/Data Science Challange/transactions_training_sept_oct_2023.csv'
df_train = pd.read_csv(train_data_path, sep=';', decimal=',')
df_train

,ID_TRX,ID_CARD,DATETIME_GMT,AMOUNT,Anomaly_amount_1,Anomaly_amount_2,Anomaly_amount_3,Anomaly_amount_4,Anomaly_amount_5,Anomaly_amount_6,...,Anomaly_amount_9,Population_Anomaly_1,Population_Anomaly_2,Population_Anomaly_3,Population_Anomaly_4,Population_Anomaly_5,Population_Anomaly_6,Population_Anomaly_7,Population_Anomaly_8,FLAG_FRAUD
1,196339525,54309097,2023-09-17 00:57:00,85.0,-0.352941,-0.576471,-0.715966,-0.753753,-0.746869,NaN,...,0.897436,-0.686851,3.789623,3.823200,3.671102,3.693230,3.738034,-0.313725,-0.235294,0
2,196339531,37160392,2023-09-17 01:47:00,370.0,-1.000000,-0.181622,-0.309009,-0.309009,-0.359459,NaN,...,1.490041,-1.000000,-0.643916,-0.645737,-0.660150,-0.669171,-0.668452,0.428829,-0.041081,0
3,196339546,36562573,2023-09-17 02:07:00,350.0,-0.434286,-0.577143,-0.611429,-0.703686,-0.468499,NaN,...,1.306902,-0.576550,-0.623568,-0.625493,-0.640730,-0.650266,-0.649507,-0.321905,-0.481143,0
4,196339729,33066184,2023-09-17 04:20:00,68.0,0.102941,0.272059,0.424632,0.314388,0.168108,NaN,...,0.481030,0.525260,0.937518,0.927608,0.849182,0.800099,0.804010,-0.303922,0.447059,0
5,196339906,27058062,2023-09-17 04:35:00,25.0,-0.200000,5.260000,3.200000,3.187879,2.830435,-2.9,...,1.091954,0.496000,4.270050,4.243095,4.029774,3.896270,3.906906,0.266667,0.160000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79996,200491842,55434187,2023-10-17 11:32:00,210.0,1.072381,0.626740,-0.044218,-0.235281,-0.235281,NaN,...,0.458422,1.290476,0.792127,0.901333,0.880144,0.867904,0.896647,0.023810,1.233333,0
79997,200491882,60191597,2023-10-17 11:32:00,200.0,0.500000,0.500000,0.500000,0.500000,0.500000,-0.4,...,0.833333,0.400000,0.881733,0.996399,0.974151,0.961299,0.991479,0.166667,0.400000,0
79998,200491890,56147789,2023-10-17 11:32:00,398.0,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,NaN,...,NaN,-1.000000,-0.054405,0.003216,-0.007964,-0.014422,0.000743,-1.000000,-1.000000,0
79999,200492009,45923750,2023-10-17 11:34:00,250.0,-1.000000,0.000000,0.000000,-0.001000,-0.000800,NaN,...,1.000000,0.016000,-0.502832,-0.480022,-0.492850,-0.510836,-0.510007,0.000000,0.000000,0
80000,200492036,55862285,2023-10-17 11:34:00,350.0,-0.244286,-0.244286,-0.358095,-0.498000,-0.498000,NaN,...,0.998217,-0.560204,0.075276,0.140800,0.128086,0.120742,0.137988,-0.573333,-0.572571,0

In [3]:
df_train = df_train.drop(columns=['ID_TRX', 'ID_CARD', 'DATETIME_GMT'])
df_train

,AMOUNT,Anomaly_amount_1,Anomaly_amount_2,Anomaly_amount_3,Anomaly_amount_4,Anomaly_amount_5,Anomaly_amount_6,Anomaly_amount_7,Anomaly_amount_8,FLAG_BEHAVIOUR_Anomaly_1,...,Anomaly_amount_9,Population_Anomaly_1,Population_Anomaly_2,Population_Anomaly_3,Population_Anomaly_4,Population_Anomaly_5,Population_Anomaly_6,Population_Anomaly_7,Population_Anomaly_8,FLAG_FRAUD
1,85.0,-0.352941,-0.576471,-0.715966,-0.753753,-0.746869,NaN,-0.294118,-1.000000,0,...,0.897436,-0.686851,3.789623,3.823200,3.671102,3.693230,3.738034,-0.313725,-0.235294,0
2,370.0,-1.000000,-0.181622,-0.309009,-0.309009,-0.359459,NaN,-1.000000,-1.000000,0,...,1.490041,-1.000000,-0.643916,-0.645737,-0.660150,-0.669171,-0.668452,0.428829,-0.041081,0
3,350.0,-0.434286,-0.577143,-0.611429,-0.703686,-0.468499,NaN,-0.531429,-1.000000,0,...,1.306902,-0.576550,-0.623568,-0.625493,-0.640730,-0.650266,-0.649507,-0.321905,-0.481143,0
4,68.0,0.102941,0.272059,0.424632,0.314388,0.168108,NaN,0.535294,-1.000000,0,...,0.481030,0.525260,0.937518,0.927608,0.849182,0.800099,0.804010,-0.303922,0.447059,0
5,25.0,-0.200000,5.260000,3.200000,3.187879,2.830435,-2.9,0.200000,-1.000000,0,...,1.091954,0.496000,4.270050,4.243095,4.029774,3.896270,3.906906,0.266667,0.160000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79996,210.0,1.072381,0.626740,-0.044218,-0.235281,-0.235281,NaN,0.314286,-0.357143,0,...,0.458422,1.290476,0.792127,0.901333,0.880144,0.867904,0.896647,0.023810,1.233333,0
79997,200.0,0.500000,0.500000,0.500000,0.500000,0.500000,-0.4,0.000000,-1.000000,0,...,0.833333,0.400000,0.881733,0.996399,0.974151,0.961299,0.991479,0.166667,0.400000,0
79998,398.0,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,NaN,-1.000000,-1.000000,1,...,NaN,-1.000000,-0.054405,0.003216,-0.007964,-0.014422,0.000743,-1.000000,-1.000000,0
79999,250.0,-1.000000,0.000000,0.000000,-0.001000,-0.000800,NaN,-1.000000,-1.000000,0,...,1.000000,0.016000,-0.502832,-0.480022,-0.492850,-0.510836,-0.510007,0.000000,0.000000,0
80000,350.0,-0.244286,-0.244286,-0.358095,-0.498000,-0.498000,NaN,-0.715714,-1.000000,0,...,0.998217,-0.560204,0.075276,0.140800,0.128086,0.120742,0.137988,-0.573333,-0.572571,0

In [4]:
# For creating a validation dataset by randomly selecting 20% of the training data
val_df = df_train.sample(frac=0.2, random_state=42)
# The remaining 80% will be used for training
train_df = df_train.drop(val_df.index)

In [5]:
train_df.isna().values.any()

True

In [6]:
# The dataset is very imbalanced, with a majority of transactions being non-fraudulent (0) and a minority being fraudulent (1).
# We may count how many fraudulent transactions there are in the training set.
fraud_count = df_train['FLAG_FRAUD'].value_counts()
print(fraud_count)

FLAG_FRAUD
0    79953
1       47
Name: count, dtype: int64

In [7]:
# A ratio between the number of non-fraudulent and fraudulent transactions, to the nearest integer.
ratio = fraud_count[0] // fraud_count[1]
ratio

1701

#### Method 1: logistic regression for classification

Considering there are NA values, we may apply two methods:

1. Replace them with 0 (which might be heavily biased).

2. Drop the columns with a lot of NA values.

In [8]:
# Method 1: replace NA values with 0
train_df = train_df.fillna(0)
val_df = val_df.fillna(0)

In [9]:
# Define the feature data (X), feature names, and target data (y), for both training and valing data
X_train = train_df.iloc[:, :26].values  # values for training feature data
y_train = train_df.iloc[:, -1].values  # values for target data (training labels)
X_val = val_df.iloc[:, :26].values  # values for validation feature data
y_val = val_df.iloc[:, -1].values  # values for target data (validation

feature_names = list(df_train.columns[:26])  # 25 design properties

# Quick chek of the shape
X_train.shape, y_train.shape, X_val.shape, y_val.shape, feature_names

((64000, 26),
 (64000,),
 (16000, 26),
 (16000,),
 ['AMOUNT',
  'Anomaly_amount_1',
  'Anomaly_amount_2',
  'Anomaly_amount_3',
  'Anomaly_amount_4',
  'Anomaly_amount_5',
  'Anomaly_amount_6',
  'Anomaly_amount_7',
  'Anomaly_amount_8',
  'FLAG_BEHAVIOUR_Anomaly_1',
  'FLAG_BEHAVIOUR_Anomaly_2',
  'FLAG_BEHAVIOUR_Anomaly_3',
  'FLAG_BEHAVIOUR_Anomaly_4',
  'FLAG_BEHAVIOUR_Anomaly_5',
  'FLAG_BEHAVIOUR_Anomaly_6',
  'FLAG_BEHAVIOUR_Anomaly7',
  'FLAG_BEHAVIOUR_Anomaly_8',
  'Anomaly_amount_9',
  'Population_Anomaly_1',
  'Population_Anomaly_2',
  'Population_Anomaly_3',
  'Population_Anomaly_4',
  'Population_Anomaly_5',
  'Population_Anomaly_6',
  'Population_Anomaly_7',
  'Population_Anomaly_8'])

In [10]:
# Fit a standard logistic regression model
lr_model = LogisticRegression(solver='lbfgs', max_iter=1000, random_state=42)
lr_model.fit(X_train, y_train)

# Make predictions with the standard model
y_pred_train_lr = lr_model.predict(X_train)
y_pred_val_lr = lr_model.predict(X_val)

# Evaluate the standard model
print(classification_report(y_train, y_pred_train_lr))
print(classification_report(y_val, y_pred_val_lr))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     63964
           1       1.00      0.11      0.20        36

    accuracy                           1.00     64000
   macro avg       1.00      0.56      0.60     64000
weighted avg       1.00      1.00      1.00     64000

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     15989
           1       0.00      0.00      0.00        11

    accuracy                           1.00     16000
   macro avg       0.50      0.50      0.50     16000
weighted avg       1.00      1.00      1.00     16000

c:\Users\brian\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\brian\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\brian\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [11]:
# Fit a weighted logistic regression model
weights = {0: 1, 1: ratio}  # our weights would be the ratio of non-fraudulent to fraudulent transactions
weighted_lr_model = LogisticRegression(solver='lbfgs', max_iter=1000, random_state=42, class_weight=weights)
weighted_lr_model.fit(X_train, y_train)

# Make predictions with the weighted model
y_pred_train_weighted_lr = weighted_lr_model.predict(X_train)
y_pred_val_weighted_lr = weighted_lr_model.predict(X_val)

# Evaluate the weighted model
print(classification_report(y_train, y_pred_train_weighted_lr))
print(classification_report(y_val, y_pred_val_weighted_lr))

              precision    recall  f1-score   support

           0       1.00      0.97      0.98     63964
           1       0.02      0.97      0.03        36

    accuracy                           0.97     64000
   macro avg       0.51      0.97      0.51     64000
weighted avg       1.00      0.97      0.98     64000

              precision    recall  f1-score   support

           0       1.00      0.96      0.98     15989
           1       0.02      0.91      0.03        11

    accuracy                           0.96     16000
   macro avg       0.51      0.94      0.51     16000
weighted avg       1.00      0.96      0.98     16000

c:\Users\brian\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [12]:
test_data_path = 'D:/University documents/Year 4/Data Science Challange/transactions_unclassified_2023.csv'
df_test = pd.read_csv(test_data_path, sep=';', decimal=',')
df_test = df_test.drop(columns=['ID_TRX', 'ID_CARD', 'DATETIME_GMT'])
df_test = df_test.fillna(0)

In [13]:
X_test = df_test.iloc[:, :25].values  # values for test feature data

# Prediction by using the weighted logistic regression model above
y_pred_test_weighted_lr = weighted_lr_model.predict(X_val)
y_pred_test_weighted_lr

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [14]:
df_train

,AMOUNT,Anomaly_amount_1,Anomaly_amount_2,Anomaly_amount_3,Anomaly_amount_4,Anomaly_amount_5,Anomaly_amount_6,Anomaly_amount_7,Anomaly_amount_8,FLAG_BEHAVIOUR_Anomaly_1,...,Anomaly_amount_9,Population_Anomaly_1,Population_Anomaly_2,Population_Anomaly_3,Population_Anomaly_4,Population_Anomaly_5,Population_Anomaly_6,Population_Anomaly_7,Population_Anomaly_8,FLAG_FRAUD
1,85.0,-0.352941,-0.576471,-0.715966,-0.753753,-0.746869,NaN,-0.294118,-1.000000,0,...,0.897436,-0.686851,3.789623,3.823200,3.671102,3.693230,3.738034,-0.313725,-0.235294,0
2,370.0,-1.000000,-0.181622,-0.309009,-0.309009,-0.359459,NaN,-1.000000,-1.000000,0,...,1.490041,-1.000000,-0.643916,-0.645737,-0.660150,-0.669171,-0.668452,0.428829,-0.041081,0
3,350.0,-0.434286,-0.577143,-0.611429,-0.703686,-0.468499,NaN,-0.531429,-1.000000,0,...,1.306902,-0.576550,-0.623568,-0.625493,-0.640730,-0.650266,-0.649507,-0.321905,-0.481143,0
4,68.0,0.102941,0.272059,0.424632,0.314388,0.168108,NaN,0.535294,-1.000000,0,...,0.481030,0.525260,0.937518,0.927608,0.849182,0.800099,0.804010,-0.303922,0.447059,0
5,25.0,-0.200000,5.260000,3.200000,3.187879,2.830435,-2.9,0.200000,-1.000000,0,...,1.091954,0.496000,4.270050,4.243095,4.029774,3.896270,3.906906,0.266667,0.160000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79996,210.0,1.072381,0.626740,-0.044218,-0.235281,-0.235281,NaN,0.314286,-0.357143,0,...,0.458422,1.290476,0.792127,0.901333,0.880144,0.867904,0.896647,0.023810,1.233333,0
79997,200.0,0.500000,0.500000,0.500000,0.500000,0.500000,-0.4,0.000000,-1.000000,0,...,0.833333,0.400000,0.881733,0.996399,0.974151,0.961299,0.991479,0.166667,0.400000,0
79998,398.0,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,NaN,-1.000000,-1.000000,1,...,NaN,-1.000000,-0.054405,0.003216,-0.007964,-0.014422,0.000743,-1.000000,-1.000000,0
79999,250.0,-1.000000,0.000000,0.000000,-0.001000,-0.000800,NaN,-1.000000,-1.000000,0,...,1.000000,0.016000,-0.502832,-0.480022,-0.492850,-0.510836,-0.510007,0.000000,0.000000,0
80000,350.0,-0.244286,-0.244286,-0.358095,-0.498000,-0.498000,NaN,-0.715714,-1.000000,0,...,0.998217,-0.560204,0.075276,0.140800,0.128086,0.120742,0.137988,-0.573333,-0.572571,0

In [15]:
# Now we apply method 2, where we will check NaN values in the dataset first

# Series of counts of NaNs per column
nan_counts = df_train.isna().sum()

# Filter to only those with missing values
nan_counts = nan_counts[nan_counts > 0]
print(nan_counts)

Anomaly_amount_6    43667
Anomaly_amount_9    19816
dtype: int64

In [16]:
# We would further drop these two columns from the dataset including a lot of NaN values (missing data)
df_train = df_train.drop(columns=['Anomaly_amount_6', 'Anomaly_amount_9'])

In [17]:
# For creating a validation dataset by randomly selecting 20% of the training data
val_df = df_train.sample(frac=0.2, random_state=42)
# The remaining 80% will be used for training
train_df = df_train.drop(val_df.index)

In [19]:
train_df

,AMOUNT,Anomaly_amount_1,Anomaly_amount_2,Anomaly_amount_3,Anomaly_amount_4,Anomaly_amount_5,Anomaly_amount_7,Anomaly_amount_8,FLAG_BEHAVIOUR_Anomaly_1,FLAG_BEHAVIOUR_Anomaly_2,...,FLAG_BEHAVIOUR_Anomaly_8,Population_Anomaly_1,Population_Anomaly_2,Population_Anomaly_3,Population_Anomaly_4,Population_Anomaly_5,Population_Anomaly_6,Population_Anomaly_7,Population_Anomaly_8,FLAG_FRAUD
1,85.0,-0.352941,-0.576471,-0.715966,-0.753753,-0.746869,-0.294118,-1.000000,0,0,...,0,-0.686851,3.789623,3.823200,3.671102,3.693230,3.738034,-0.313725,-0.235294,0
2,370.0,-1.000000,-0.181622,-0.309009,-0.309009,-0.359459,-1.000000,-1.000000,0,1,...,0,-1.000000,-0.643916,-0.645737,-0.660150,-0.669171,-0.668452,0.428829,-0.041081,0
3,350.0,-0.434286,-0.577143,-0.611429,-0.703686,-0.468499,-0.531429,-1.000000,0,0,...,0,-0.576550,-0.623568,-0.625493,-0.640730,-0.650266,-0.649507,-0.321905,-0.481143,0
4,68.0,0.102941,0.272059,0.424632,0.314388,0.168108,0.535294,-1.000000,0,0,...,0,0.525260,0.937518,0.927608,0.849182,0.800099,0.804010,-0.303922,0.447059,0
5,25.0,-0.200000,5.260000,3.200000,3.187879,2.830435,0.200000,-1.000000,0,0,...,0,0.496000,4.270050,4.243095,4.029774,3.896270,3.906906,0.266667,0.160000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79996,210.0,1.072381,0.626740,-0.044218,-0.235281,-0.235281,0.314286,-0.357143,0,0,...,0,1.290476,0.792127,0.901333,0.880144,0.867904,0.896647,0.023810,1.233333,0
79997,200.0,0.500000,0.500000,0.500000,0.500000,0.500000,0.000000,-1.000000,0,0,...,0,0.400000,0.881733,0.996399,0.974151,0.961299,0.991479,0.166667,0.400000,0
79998,398.0,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,1,0,...,0,-1.000000,-0.054405,0.003216,-0.007964,-0.014422,0.000743,-1.000000,-1.000000,0
79999,250.0,-1.000000,0.000000,0.000000,-0.001000,-0.000800,-1.000000,-1.000000,0,0,...,0,0.016000,-0.502832,-0.480022,-0.492850,-0.510836,-0.510007,0.000000,0.000000,0
80000,350.0,-0.244286,-0.244286,-0.358095,-0.498000,-0.498000,-0.715714,-1.000000,0,0,...,0,-0.560204,0.075276,0.140800,0.128086,0.120742,0.137988,-0.573333,-0.572571,0

In [21]:
# Define the feature data (X), feature names, and target data (y), for both training and valing data
X_train = train_df.iloc[:, :24].values  # values for training feature data
y_train = train_df.iloc[:, -1].values  # values for target data (training labels)
X_val = val_df.iloc[:, :24].values  # values for validation feature data
y_val = val_df.iloc[:, -1].values  # values for target data (validation

feature_names = list(df_train.columns[:24])

# Quick chek of the shape
X_train.shape, y_train.shape, X_val.shape, y_val.shape, feature_names

((64000, 24),
 (64000,),
 (16000, 24),
 (16000,),
 ['AMOUNT',
  'Anomaly_amount_1',
  'Anomaly_amount_2',
  'Anomaly_amount_3',
  'Anomaly_amount_4',
  'Anomaly_amount_5',
  'Anomaly_amount_7',
  'Anomaly_amount_8',
  'FLAG_BEHAVIOUR_Anomaly_1',
  'FLAG_BEHAVIOUR_Anomaly_2',
  'FLAG_BEHAVIOUR_Anomaly_3',
  'FLAG_BEHAVIOUR_Anomaly_4',
  'FLAG_BEHAVIOUR_Anomaly_5',
  'FLAG_BEHAVIOUR_Anomaly_6',
  'FLAG_BEHAVIOUR_Anomaly7',
  'FLAG_BEHAVIOUR_Anomaly_8',
  'Population_Anomaly_1',
  'Population_Anomaly_2',
  'Population_Anomaly_3',
  'Population_Anomaly_4',
  'Population_Anomaly_5',
  'Population_Anomaly_6',
  'Population_Anomaly_7',
  'Population_Anomaly_8'])

In [22]:
# Fit a weighted logistic regression model
weights = {0: 1, 1: ratio}  # our weights would be the ratio of non-fraudulent to fraudulent transactions
weighted_lr_model = LogisticRegression(solver='lbfgs', max_iter=1000, random_state=42, class_weight=weights)
weighted_lr_model.fit(X_train, y_train)

# Make predictions with the weighted model
y_pred_train_weighted_lr = weighted_lr_model.predict(X_train)
y_pred_val_weighted_lr = weighted_lr_model.predict(X_val)

# Evaluate the weighted model
print(classification_report(y_train, y_pred_train_weighted_lr))
print(classification_report(y_val, y_pred_val_weighted_lr))

              precision    recall  f1-score   support

           0       1.00      0.97      0.98     63964
           1       0.02      0.97      0.03        36

    accuracy                           0.97     64000
   macro avg       0.51      0.97      0.51     64000
weighted avg       1.00      0.97      0.98     64000

              precision    recall  f1-score   support

           0       1.00      0.96      0.98     15989
           1       0.02      0.91      0.03        11

    accuracy                           0.96     16000
   macro avg       0.51      0.94      0.51     16000
weighted avg       1.00      0.96      0.98     16000

c:\Users\brian\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(